# Form implementation generated from reading ui file 'graphic_main.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(720, 686)
        Dialog.setMinimumSize(QtCore.QSize(720, 400))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menu_up = QtWidgets.QFrame(Dialog)
        self.menu_up.setMinimumSize(QtCore.QSize(720, 60))
        self.menu_up.setMaximumSize(QtCore.QSize(16777215, 60))
        self.menu_up.setStyleSheet("background-color: rgb(100, 100, 100);")
        self.menu_up.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu_up.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu_up.setObjectName("menu_up")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.menu_up)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.menu_up)
        self.frame_2.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Button_Exit = QtWidgets.QPushButton(self.frame_4)
        self.Button_Exit.setMinimumSize(QtCore.QSize(70, 23))
        self.Button_Exit.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    background-color: rgb(109, 109, 109);\n"
"    border-radius: 3px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(136, 136, 136);\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Button_Exit.setObjectName("Button_Exit")
        self.horizontalLayout_2.addWidget(self.Button_Exit)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_Search = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_Search.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_Search.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(30,30,30);\n"
"    border-radius: 0px;\n"
"    border: 1px solid rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.lineEdit_Search.setObjectName("lineEdit_Search")
        self.horizontalLayout_6.addWidget(self.lineEdit_Search)
        self.Button_Search = QtWidgets.QPushButton(self.frame_5)
        self.Button_Search.setMinimumSize(QtCore.QSize(70, 25))
        self.Button_Search.setMaximumSize(QtCore.QSize(70, 16777215))
        self.Button_Search.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    background-color: rgb(109, 109, 109);\n"
"    border-color:rgb(130, 130, 130);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(136, 136, 136);\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Button_Search.setObjectName("Button_Search")
        self.horizontalLayout_6.addWidget(self.Button_Search)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7.addWidget(self.frame_6)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMinimumSize(QtCore.QSize(250, 0))
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Button_Show_Check = QtWidgets.QPushButton(self.frame)
        self.Button_Show_Check.setMinimumSize(QtCore.QSize(0, 25))
        self.Button_Show_Check.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    background-color: rgb(109, 109, 109);\n"
"    border-radius: 3px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(136, 136, 136);\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Button_Show_Check.setObjectName("Button_Show_Check")
        self.horizontalLayout_8.addWidget(self.Button_Show_Check)
        self.Button_Reset = QtWidgets.QPushButton(self.frame)
        self.Button_Reset.setMinimumSize(QtCore.QSize(0, 25))
        self.Button_Reset.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    background-color: rgb(109, 109, 109);\n"
"    border-radius: 3px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(136, 136, 136);\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Button_Reset.setObjectName("Button_Reset")
        self.horizontalLayout_8.addWidget(self.Button_Reset)
        self.Button_Save_Check = QtWidgets.QPushButton(self.frame)
        self.Button_Save_Check.setMinimumSize(QtCore.QSize(0, 25))
        self.Button_Save_Check.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    background-color: rgb(109, 109, 109);\n"
"    border-radius: 3px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(136, 136, 136);\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Button_Save_Check.setObjectName("Button_Save_Check")
        self.horizontalLayout_8.addWidget(self.Button_Save_Check)
        self.horizontalLayout_7.addWidget(self.frame)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.menu_up)
        self.menu_down = QtWidgets.QFrame(Dialog)
        self.menu_down.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.menu_down.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.menu_down.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu_down.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu_down.setObjectName("menu_down")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menu_down)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.menu_down)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1_All = QtWidgets.QWidget()
        self.page_1_All.setObjectName("page_1_All")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_1_All)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.table_for_cards = QtWidgets.QTableWidget(self.page_1_All)
        self.table_for_cards.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.table_for_cards.setStyleSheet("QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(32, 34, 42);\n"
"    background-color:rgb(53, 53, 53);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    border-radius: 0px;\n"
" }")
        self.table_for_cards.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.table_for_cards.setAutoScroll(False)
        self.table_for_cards.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.AnyKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed)
        self.table_for_cards.setRowCount(5)
        self.table_for_cards.setColumnCount(4)
        self.table_for_cards.setObjectName("table_for_cards")
        self.table_for_cards.horizontalHeader().setVisible(False)
        self.table_for_cards.horizontalHeader().setCascadingSectionResizes(False)
        self.table_for_cards.horizontalHeader().setDefaultSectionSize(130)
        self.table_for_cards.horizontalHeader().setHighlightSections(False)
        self.table_for_cards.horizontalHeader().setStretchLastSection(True)
        self.table_for_cards.verticalHeader().setVisible(False)
        self.table_for_cards.verticalHeader().setHighlightSections(False)
        self.table_for_cards.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_5.addWidget(self.table_for_cards)
        self.menu_right = QtWidgets.QFrame(self.page_1_All)
        self.menu_right.setMinimumSize(QtCore.QSize(120, 0))
        self.menu_right.setMaximumSize(QtCore.QSize(120, 16777215))
        self.menu_right.setStyleSheet("")
        self.menu_right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu_right.setObjectName("menu_right")
        self.frame_7 = QtWidgets.QFrame(self.menu_right)
        self.frame_7.setGeometry(QtCore.QRect(0, 10, 125, 40))
        self.frame_7.setMinimumSize(QtCore.QSize(110, 40))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Regions_Box = QtWidgets.QComboBox(self.frame_7)
        self.Regions_Box.setMinimumSize(QtCore.QSize(115, 25))
        self.Regions_Box.setMaximumSize(QtCore.QSize(115, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.Regions_Box.setFont(font)
        self.Regions_Box.setStyleSheet("QComboBox {\n"
"    border: 1px solid;\n"
"    background-color: rgb(109, 109, 109);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: rgb(133, 133, 133);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox:pressed {    \n"
"    background-color: rgb(133, 133, 133);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Regions_Box.setObjectName("Regions_Box")
        self.Regions_Box.addItem("")
        self.Regions_Box.addItem("")
        self.Regions_Box.addItem("")
        self.verticalLayout_2.addWidget(self.Regions_Box)
        self.horizontalLayout_5.addWidget(self.menu_right)
        self.stackedWidget.addWidget(self.page_1_All)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.menu_down)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Button_Exit.setText(_translate("Dialog", "Exit"))
        self.lineEdit_Search.setText(_translate("Dialog", "Enter words"))
        self.Button_Search.setText(_translate("Dialog", "Search"))
        self.Button_Show_Check.setText(_translate("Dialog", "Show Check"))
        self.Button_Reset.setText(_translate("Dialog", "Reset"))
        self.Button_Save_Check.setText(_translate("Dialog", "Save"))
        self.table_for_cards.setSortingEnabled(True)
        self.Regions_Box.setItemText(0, _translate("Dialog", "All regions"))
        self.Regions_Box.setItemText(1, _translate("Dialog", "Moscow"))
        self.Regions_Box.setItemText(2, _translate("Dialog", "Moscow region"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
